--- 
- name: Update banner message
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    banner_message:  "__\ntest \ d___"
  tasks:
  - name: "Update banner message to '{{ banner_message }}'"
    ios_config:
      lines:
        - "banner motd % {{ banner_message }} %"
