--- 
- name: Update banner message
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    banner_message:  " ___      ___ _________        ___  ___  ________  ___  __    ___  _______   ________      \n|\  \    /  /|\___   ___\     |\  \|\  \|\   __  \|\  \|\  \ |\  \|\  ___ \ |\   ____\     \n\ \  \  /  / ||___ \  \_|     \ \  \\\  \ \  \|\  \ \  \/  /|\ \  \ \   __/|\ \  \___|_    \n \ \  \/  / /     \ \  \       \ \   __  \ \  \\\  \ \   ___  \ \  \ \  \_|/_\ \_____  \   \n  \ \    / /       \ \  \       \ \  \ \  \ \  \\\  \ \  \\ \  \ \  \ \  \_|\ \|____|\  \  \n   \ \__/ /         \ \__\       \ \__\ \__\ \_______\ \__\\ \__\ \__\ \_______\____\_\  \ \n    \|__|/           \|__|        \|__|\|__|\|_______|\|__| \|__|\|__|\|_______|\_________\\n                                                                               \|_________|"
                                                                                           "
  tasks:
  - name: "Update banner message to '{{ banner_message }}'"
    ios_config:
      lines:
        - "banner motd % {{ banner_message }} %"
